import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from '@/components/Navbar';
import Footer from "@/components/Footer";

import Provide from "@/components/Providers";

const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Furniro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Provide>
    <html lang="en">
    
      <body className={inter.className}>

    
      <Navbar />{children}  <Footer />
     </body>
    </html>
    </Provide>
  );
}
